[project]
name = "league-of-legends-mcp"
version = "0.1.0"
description = "Model Context Protocol server for League of Legends champion information"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.14.0",
]
